tasks:
  - name: setup
    init: |
      sudo rm -rf /home/gitpod/.rustup/
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      rustup component add clippy
      rustup target add x86_64-unknown-linux-musl
      make run

vscode:
  extensions:
    - rust-lang.rust-analyzer
    - tamasfe.even-better-toml
    - github.copilot
