name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04
    container: ubuntu:20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          apt update && apt install g++

      - name: cxx
        run: |
          make cxx && make run_cxx