name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          lscpu

      - name: Dep
        run: |
          docker build -t local .

      - name: cxx
        run: |
          docker run local bash -c "make cxx && make run_cxx"

      - name: c
        run: |
          docker run local bash -c "make cxx_so && make c && make run_c"

      - name: rust
        run: |
          docker run local bash -c "make cxx_so && make run_rust"